### ISSUE TITLE
[Bug] Missing Card

### ISSUE THREAD

**Issue by supermamie** [Pheonyxior/Pirate-Solitaire-Git-Repo#4]
I have no idea how I managed this but a card is missing.
![Screenshot_20231124-140107_Pirate Solitaire](https://github.com/Pheonyxior/Pirate-Solitaire-Git-Repo/assets/693751/03cc978e-1c40-4d45-b941-ac7ac20384e3)

**Comment by Pheonyxior** [comment]
I'm gonna look into this, but I suspect it's because it's technically possible to pick a card while it's being discarded.

**Comment by Pheonyxior** [comment]
I've made it impossible to pick cards while they're being discarded, so I am going to consider this issue closed for now, but do not hesitate to bring it up if it happens again.
