### ISSUE TITLE
Game does not allow for moving beast and two pirates when using the top-right corner

### ISSUE THREAD

**Issue by kitroed** [Pheonyxior/Pirate-Solitaire-Git-Repo#5]
Even though the button lights up, nothing happens

https://github.com/Pheonyxior/Pirate-Solitaire-Git-Repo/assets/326780/f85c5e9a-1fed-4cd2-9999-b0a20ff089d6

**Comment by Pheonyxior** [comment]
Hi
if there are more than two pirates available, pressing the beast button toggles it, allowing you to select the two pirates you wish to discard.

**Comment by kitroed** [comment]
Oh wow, okay! Thanks for clarifying!
