### ISSUE TITLE
Visual for gathered stack

### ISSUE THREAD

**Issue by Ygarr** [Pheonyxior/Pirate-Solitaire-Git-Repo#6]
Please make difference visually: 
single beast card on the top-left
 and 
discarded beast card with two pirates under.

Not only by excerpted  line but by volume

**Comment by Ferk** [comment]
Another visual feedback detail could be fading out the buttons for the beasts that have been already completed.

**Comment by Pheonyxior** [comment]
Both of these suggestions have been implemented in the last commit so I'll mark this as closed. I don't wanna make promises, but the update should come to f-droid in the following days.
